# Artifact Keeper Plugin Manifest
# https://artifactkeeper.com/docs/advanced/plugins/

[plugin]
name = "unity-format"
version = "0.1.0"
description = "Format handler for Unity .unitypackage files (gzipped tarballs)"
author = "Artifact Keeper Team"
license = "MIT"
homepage = "https://github.com/artifact-keeper/artifact-keeper-example-plugin"
min_keeper_version = "1.0.0"

[format]
key = "unity"
display_name = "Unity Package"
extensions = [".unitypackage"]
content_types = ["application/gzip", "application/x-gzip"]

[capabilities]
parse_metadata = true
validate_artifact = true
generate_index = true

[resources]
max_memory_bytes = 16777216   # 16 MB
max_fuel = 100000000          # 100M cycles
max_execution_ms = 10000      # 10 seconds
